### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Titaniumtown** [helixd2s/MineVKR#2]
You talked about https://github.com/hyperearth/JiviX in the README. So will this mod bring Vulkan support to minecraft? Along with RTX ray tracing? If so, you are doing a service to humanity, and I thank you.

Since this is RTX focused, will it still work on GTX cards, or amd cards?

What is the think in the releases page? ("LWJGL-3.2.3 with Vulkan API for MultiMC") is that just the mod itself?

Does this also work on previous versions of MC? Like can I use minecraft 1.12.2 with this?

If Vulkan support is being brought to mc, will that make the game faster?

**Comment by helixd-2k18** [comment]
Project currently incomplete, planned fully rewrite and rebase code... 
I will give further instructions after the first beta...
