### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Titaniumtown** [helixd2s/MineVKR#3]
I don't know how I could install this mod. Please put something in the readme!

**Comment by Titaniumtown** [comment]
I figured it out, I replace the folder in ~/.minecraft/libraries/org/ right?

**Comment by Titaniumtown** [comment]
How would I do this in multimc?

**Comment by arceuss** [comment]
did u ever manage to get it working

**Comment by Titaniumtown** [comment]
nope

**Comment by helixd-2k18** [comment]
Project currently incomplete, planned fully rewrite and rebase code...
