### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by Titaniumtown** [helixd2s/MineVKR#4]
I'm on arch linux.

I ran:
./gradlew build

Output:
```
> Task :sourcesJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sourcesJar'.
> Couldn't follow symbolic link '/home/simon/MineVKR/src/main/java/lib/jniJiviXBase.lib'
```

I did use `git clone -c core.symlinks=true https://github.com/hyperearth/MineVKR.git --recursive` to clone repo

**Comment by arceuss** [comment]
it builds for me but idk where anything goes

**Comment by helixd-2k18** [comment]
Project currently incomplete, planned fully rewrite and rebase code...
